version: "3"
services:
  app:
    restart: always
    build: .
    command: gunicorn --timeout=30 --workers=4 --bind :3030 wsgi:application
    expose:
      - "3030"
    depends_on:
      - db
    networks:
      - db_network
      - web_network

  db:
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - db_network

  nginx:
    restart: always
    image: nginx
    ports:
      - "3030:3030"
    volumes:
      - "./config/nginx:/etc/nginx/conf.d"
    depends_on:
      - app
    networks:
      - web_network


  elastic_search:
    restart: always
    image: nshou/elasticsearch-kibana
    ports:
      - "9200:9200"
      - "5601:5601"

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
